name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Run tests with coverage
        run: |
           python3 -m pip install coverage
           coverage run -m unittest
           coverage xml -o .qodana/code-coverage/coverage.xml
      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
           name: py-coverage-data
           path: PYTHON/py/.qodana/code-coverage
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        with:
          args: --baseline, qodana.sarif.json, -i,PYTHON/py,
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          
